---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jameslendrem.
--- DateTime: 11/11/2023 14:31
---

import "CoreLibs/crank"
import "CrankWindow"

local pd <const> = playdate
local gfx <const> = pd.graphics

class("CrankMenu").extends(gfx.sprite)

function CrankMenu:init()
    CrankMenu.super.init(self);
    self.selectedWindow = 1;
    self.windows = {}

    for index = 1,6,1 do

        print(index, self.selectedWindow, index == self.selectedWindow)
        -- self.windows[index + 1] = Sprite();
        self.windows[index] = CrankWindow(400 - 32, 6 + 38 * (index - 1), index == self.selectedWindow)
        -- displayWindow(6, 6 + 38 * index, index == self.selectedWindow);
    end

    local menuImage = gfx.image.new(40, 240)

    self:setCenter(0, 0)
    self:moveTo(400 - 40, 0)


    gfx.pushContext(menuImage)
        gfx.setColor(gfx.kColorBlack)
        gfx.fillRect(0, 0, 40, 240)
    gfx.popContext()

    gfx.setColor(gfx.kColorWhite)

    -- self:setZIndex(50)

    self:setVisible(true)
    self:setImage(menuImage)
    self:add();
end

function CrankMenu:update()
    self:setVisible(not pd.isCrankDocked())


    local crankTicks <const> = pd.getCrankTicks(6)

    if (crankTicks > 0) then

        self.selectedWindow = (self.selectedWindow + 1) % 7;

        if (self.selectedWindow == 0) then
            self.selectedWindow = 1;
        end

    end

    for index, windows in pairs(self.windows) do

        if crankTicks > 0 then
            self.windows[index]:remove()
            self.windows[index] = CrankWindow(400 -32, 6 + 38 * (index - 1), index == self.selectedWindow)
        end

        self.windows[index]:setVisible(self:isVisible());

    end


end