---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jameslendrem.
--- DateTime: 11/11/2023 15:29
---

local pd <const> = playdate;
local gfx <const> = pd.graphics;

class("CrankWindow").extends(gfx.sprite);

function CrankWindow:init(x, y, selected)
    CrankWindow.super.init(self);

    self.selected = selected

    local windowImage = gfx.image.new(32, 32)

    self:setCenter(0, 0)
    self:moveTo(x, y);

    gfx.pushContext(windowImage)
    gfx.setColor(gfx.kColorWhite);

    gfx.fillRect(0, 0, 32, 32);
    if (self.selected) then
        gfx.setColor(gfx.kColorBlack)
        gfx.drawRect(2, 2, 28, 28)
    end

    gfx.popContext();

    self:setZIndex(32)
    self:setVisible(true);
    self:setImage(windowImage);
    self:add()

end

function CrankWindow:select(selected)
    self.selected = selected
    self:markDirty();
end