---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jameslendrem.
--- DateTime: 10/11/2023 23:06
---

local pd <const> = playdate;
local gfx <const> = pd.graphics;

import 'IsometricSquare'

class("IsometricCube").extends(gfx.sprite);

function IsometricCube:init(x, y, size)

    self.size = 16;

    if (size) then
        self.size = size
    end

    print(self.size)

    --- What the fuck is wrong with me?

    local startXPos = 0
    local startYPos = self.size / 2
    local distance = self.size

    --- IsometricCusuper.init(self)
    self:moveTo(x, y);
    local isoCubeImage = gfx.image.new(self.size * 2, self.size * 2);
    drawIsometricSquareToContext(startXPos, startYPos, distance,isoCubeImage)

    drawIsometricSquareToContext(startXPos, startYPos + distance, distance, isoCubeImage, {
        true, true, false, false
    })

    gfx.pushContext(isoCubeImage)

        gfx.setColor(gfx.kColorWhite);

        local pointsTable <const> = {
            startXPos + 1, startYPos + 1,
            startXPos + 1, startYPos + distance,
            startXPos + distance, startYPos + distance * 1.5 -1,
            startXPos + distance, startYPos + distance * 0.5,
            startXPos + 1, startYPos + 1,
        }

        gfx.fillPolygon(table.unpack(pointsTable))

        local oldXPos = startXPos;
        local oldYPos = startYPos;

        startXPos = startXPos + distance;
        startYPos = startYPos + distance / 2;

        local pointsTable <const> = {
            startXPos + 1, startYPos + 1,
            startXPos + 1, startYPos + distance - 1,
            startXPos + distance, startYPos + distance * 0.5 - 1,
            startXPos + distance, startYPos - distance * 0.5 + 1,
            startXPos + 1, startYPos + 1,
        }

        startXPos = oldXPos
        startYPos = oldYPos

        gfx.fillPolygon(table.unpack(pointsTable))

        gfx.setColor(gfx.kColorBlack);

        startYPos = startYPos + distance

        gfx.drawLine(startXPos, startYPos - distance, startXPos, startYPos)
        gfx.drawLine(startXPos + distance, startYPos + distance / 2, startXPos + distance, startYPos - distance / 2)
        gfx.drawLine(startXPos + distance * 2 - 1, startYPos, startXPos + distance * 2 - 1,startYPos - distance)

    --- self:setCollideRect(0, 0, 32, 32)
    gfx.popContext()

    self:setImage(isoCubeImage)
    self:add();
end

function IsometricCube:update()


end