---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jameslendrem.
--- DateTime: 11/11/2023 09:14
---

import "IsometricCube"

local pd <const> = playdate;
local gfx <const> = pd.gfx;

class("MovableIsoCube").extends(IsometricCube)

function MovableIsoCube:init(x, y, size)
    MovableIsoCube.super.init(self, x, y)
    self.isLockedToGrid = true;
end

function MovableIsoCube:calcMvDistance()
    local moveByDistance = self.size;
    if (not self.isLockedToGrid) then
        moveByDistance = 2;
    end
    return moveByDistance
end

--- Using cardinals as it's easy to name.
function MovableIsoCube:mvNorthEast()
    local moveByDistance = self:calcMvDistance()
    self:moveBy(moveByDistance, -moveByDistance / 2)

end

function MovableIsoCube:mvSouthEast()
    local moveByDistance = self:calcMvDistance()
    self:moveBy(moveByDistance, moveByDistance / 2)
end

function MovableIsoCube:mvSouthWest()
    local moveByDistance = self:calcMvDistance()
    self:moveBy(-moveByDistance, moveByDistance / 2)

end

function MovableIsoCube:mvNorthWest()
    local moveByDistance = self:calcMvDistance()
    self:moveBy(-moveByDistance, -moveByDistance / 2)
end

function MovableIsoCube:update()

    if (pd.buttonJustPressed(pd.kButtonDown)) then
        --- if (self.y < (240 - playerSize / 2)) then
            self:mvSouthWest()
        --- end
    end

    if (pd.buttonJustPressed(pd.kButtonUp)) then
        self:mvNorthEast()
    end

    if (pd.buttonJustPressed(pd.kButtonRight)) then
        self:mvSouthEast()
    end

    if (pd.buttonJustPressed(pd.kButtonLeft)) then
        self:mvNorthWest()
    end

end